kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv-v1
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/data/db"
